#!/bin/sh
set -e
/home/korpy/development/Fiji/fivm-rtdroid/bin/fivmc --max-threads=110 --r-max-os-threads=110 --more-opt --r-nanos-per-tick=100000 --r-thr-stack-size=300000 --gc CMR --rt-library=RTSJ -o jpapbench /home/korpy/development/paparazzi_in_java.git/jpapabench-build/output/jar/jpapabench-pj.jar /home/korpy/development/paparazzi_in_java.git/jpapabench-build/output/jar/jpapabench-core.jar /home/korpy/development/paparazzi_in_java.git/jpapabench-build/output/jar/jpapabench-core-flightplans.jar -v 1 "$@"
